---
title: "Reproducible Research - Peer Assessment 2"
author: "Kevin E. D'Elia"
date: "09/18/2015"
output: html_document
---

# Title
Your document should have a title that briefly summarizes your data analysis

# Synopsis
describes and summarizes your analysis in at most 10 complete sentences.

# Data Processing


storm.data <- read.csv(bzfile("./data/repdata_data_StormData.csv.bz2"))
str(storm.data)
names(storm.data)
unique(storm.data$EVTYPE)
table(toupper(storm.data$EVTYPE))
sort(unique(trimws(storm.data$EVTYPE)))
sort(unique(trimws(toupper(storm.data$EVTYPE))))

0. select only the columns that make sense for the analysis
1. work with the EVTYPE column first
2. remove the ? since there is no mapping for unknown types
3. replace the column with trimmed, uppercase versions

You can plot fatalities/injuries
you can plot two-panel across states


Astronomical Low Tide
Avalanche
Blizzard
Coastal Flood
Cold/Wind Chill
Debris Flow
Dense Fog
Dense Smoke
Drought
Dust Devil
Dust Storm
Excessive Heat
Extreme Cold/Wind Chill
Flash Flood
Flood
Frost/Freeze
Funnel Cloud
Freezing Fog
Hail
Heat
Heavy Rain
Heavy Snow
High Surf
High Wind

Hurricane (Typhoon)
Ice Storm
Lake-Effect Snow
Lakeshore Flood
Lightning
Marine Hail
Marine High Wind
Marine Strong Wind
Marine Thunderstorm Wind
Rip Current
Seiche
Sleet
Storm Surge/Tide
Strong Wind
Thunderstorm Wind
Tornado
Tropical Depression
Tropical Storm
Tsunami
Volcanic Ash
Waterspout
Wildfire
Winter Storm
Winter Weather





describes (in words and code) how the data were loaded into R and processed for analysis. In particular, your analysis must start from the raw CSV file containing the data. You cannot do any preprocessing outside the document. If preprocessing is time-consuming you may consider using the cache = TRUE option for certain code chunks.

Does the analysis include description and justification for any data transformations? 

Your data analysis must address the following questions:

    Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

    Across the United States, which types of events have the greatest economic consequences?

Consider writing your report as if it were to be read by a government or municipal manager who might be responsible for preparing for severe weather events and will need to prioritize resources for different types of events. However, there is no need to make any specific recommendations in your report.

# Results
in which your results are presented.

You may have other sections in your analysis, but Data Processing and Results are required.

The analysis document must have at least one figure containing a plot.

Your analyis must have no more than three figures. Figures may have multiple plots in them (i.e. panel plots), but there cannot be more than three figures total.

Do the figure(s) have descriptive captions (i.e. there is a description near the figure of what is happening in the figure)?

You must show all your code for the work in your analysis document. This may make the document a bit verbose, but that is okay. In general, you should ensure that echo = TRUE for every code chunk (this is the default setting in knitr).